# Generated by Django 5.2.4 on 2025-08-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ourService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicesTitle', models.CharField(max_length=500)),
                ('serviceDesc', models.CharField(max_length=500)),
            ],
        ),
    ]
