# Generated by Django 5.2.4 on 2025-08-18 07:41

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourServiceDetail', '0002_ourservice_descritionval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourservice',
            name='Descritionval',
            field=tinymce.models.HTMLField(default='Default description'),
        ),
    ]
