# Generated by Django 5.2.4 on 2025-08-18 16:15

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='collectFormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=250)),
                ('userEmail', models.CharField(max_length=250)),
                ('userMess', tinymce.models.HTMLField()),
            ],
        ),
    ]
