# Generated by Django 5.2.7 on 2025-10-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectformdata',
            name='userMess',
            field=models.CharField(max_length=250),
        ),
    ]
