# Generated by Django 5.2.4 on 2025-08-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rechargePlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planName', models.CharField(max_length=100)),
                ('planPrice', models.IntegerField()),
                ('planValidity', models.CharField(max_length=50)),
                ('planStar', models.CharField(max_length=50)),
                ('planData', models.CharField(max_length=50)),
                ('ValidityDescription', models.TextField()),
                ('planApi', models.CharField(max_length=100)),
            ],
        ),
    ]
