# Generated by Django 5.2.4 on 2025-08-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourServiceDetail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourservice',
            name='Descritionval',
            field=models.CharField(default='Default description', max_length=500),
        ),
    ]
