# Generated by Django 5.2.4 on 2025-08-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourServiceDetail', '0003_alter_ourservice_descritionval'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourservice',
            name='Our_image',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='new/'),
        ),
    ]
