# Generated by Django 5.2.4 on 2025-08-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourServiceDetail', '0004_ourservice_our_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourservice',
            name='Our_image',
            field=models.FileField(default=None, max_length=250, upload_to='new/'),
        ),
    ]
